name: 'xiaobei daka'

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '8 2 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests pyaes
    - name: 'Get points'
      env:
        XIAOBEI_USERNAME: ${{ secrets.XIAOBEI_USERNAME }}
        XIAOBEI_PASSWORD: ${{ secrets.XIAOBEI_PASSWORD }}
        XIAOBEI_SCKEY: ${{ secrets.XIAOBEI_SCKEY }}
      
      run: python 2.py
